name: Python Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Test get function
      run: |
        cd crc-sam/get-function
        python -m unittest discover -v
        cd ../..  

    - name: Test put function
      run: |
        cd crc-sam/put-function
        python -m unittest discover -v
        cd ../..