name: main
on: push

jobs:
  build-and-deploy-infrastructure:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub’s OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: AWS SAM setup
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: CrcGitHubActions
      - run: sam build
        working-directory: crc-sam
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: crc-sam